# Assignment


# Matrix Operation

Perform the following operations on the given matrices:
A=[[2    -1], [​0    3​]]
B=[[1   ​ 2], [-3    4​]]
a. A+B
b. AB
c. 3A−2B

In [ ]:
# a. A+B
import numpy as np
A=np.array([[2,-1],[0,3]])
B=np.array([[1,2],[-3,4]])
result=np.add(A,B)
print(f"The sum of matrix is:\n {result}")



The sum of matrix is:
 [[ 3  1]
 [-3  7]]


In [ ]:
# b. AB
import numpy as np
A=np.array([[2,-1], [0,3]])
B=np.array([[1,2],[-3,4]])
result=np.dot(A,B)
print(f"AB:\n {result}")


AB:
 [[ 5  0]
 [-9 12]]


In [ ]:
# c. 3A−2B
import numpy as np
A=np.array([[2,-1],[0,3]])
B=np.array([[1,2],[-3,4]])
a=np.dot(3,A)
b=np.dot(2,B)
result=np.subtract(a,b)
print(f"3A-2B=\n {result}")


3A-2B=
 [[ 4 -7]
 [ 6  1]]


# Determinants and Inverses  

Find the determinant of A.
Determine whether A is invertible. If yes, calculate A−1.

In [ ]:
# Find the determinant of A.
import numpy as np
import numpy.linalg as LA
A=np.array([[2,-1],[0,3]])
det_A=LA.det(A)
print(f"The determinant of A is: {det_A}")

The determinant of A is: 6.0


In [ ]:
# Determine whether A is invertible. If yes, calculate A−1.
import numpy as np
import numpy.linalg as LA
A=np.array([[2,-1],[0,3]])
det_A=LA.det(A)
print(f"The determinant of A is: {det_A}")
if(not det_A==0):
    print("Inverse of matrix A exists.")
    inverse = LA.inv(A)
    print("The inverse of the matrix A is:")
    print(inverse)
else:
    print("Inverse of matrix A doesn't exist.")

The determinant of A is: 6.0
Inverse of matrix A exists.
The inverse of the matrix A is:
[[0.5        0.16666667]
 [0.         0.33333333]]


# Eigenvalues and Eigenvectors

Compute the eigenvalues and eigenvectors of the matrix:
C=[[4    1], [​−2       1]​]

In [ ]:
import numpy as np
C = np.array([[4, 1],[-2, 1]])
eigenvalues, eigenvectors = np.linalg.eig(C)
print("Matrix C:")
print(C)
print("\nEigenvalue (first):")
print(eigenvalues[0])
print("\nCorresponding Eigenvector:")
print(eigenvectors[:, 0])

Matrix C:
[[ 4  1]
 [-2  1]]

Eigenvalue (first):
3.0

Corresponding Eigenvector:
[ 0.70710678 -0.70710678]


# Question 4

4.
You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)
car 1:
x1: 4
x2:  1.5
x3: 100
and price: 20

car 2:
x1: 6
x2:  2.0
x3: 150
and price: 30

Then, find the price of a car 3 with features
x1: 8
x2:  3.0
x3: 200
price:?

In [ ]:
import numpy as np
X=np.array([[4,1.5,100], [6,2.0,150]])
y=np.array([20,30])
x=X.T
β=np.linalg.pinv(x.dot(X)) .dot(x).dot(y)
print(f"The coefficient of β is {β} ")
car3=np.array([8,3.0,200])
price=car3.dot(β)
print(f"The price of car 3 is {price:.2f}")



The coefficient of β is [ 7.98722045e-03 -4.12114787e-13  1.99680511e-01] 
The price of car 3 is 40.00
